#!/usr/bin/env bash

# 注意：恢复前一版本成功后，因为本地 latest_released/ 下面的文件和远程不一致，
# 会导致下一次运行 binary_patch_crystal_china，尝试拷贝覆盖正在运行的文件失败。
# 此时，需要首先执行下面的命令同步远程 binary 即可。
#
# scp_crystal_china :bin/crystal_china latest_released/bin/

set -eu

binary_name=${1?Error: Input binary name, e.g. $0 crystal_china}

ROOT=${0%/*}

cd $ROOT/../bin

if ! [ -x ${binary_name} ]; then
    echo "There is no binary name: $1 in $ROOT"
    exit
fi

previous_release=$(ls -1 ${binary_name}-* |sort |tail -n1)

if [ -z "$previous_release" ]; then
    echo 'There is no previous release available.'
    exit
else
    echo "previous release file is: ${previous_release}"
fi

mv -v ${binary_name} ${binary_name}_$(date '+%Y-%m-%d_%H_%M')
mv -v ${previous_release} ${binary_name}

sudo systemctl restart ${binary_name}
systemctl status ${binary_name}
