class CommentThread < BaseModel
  def target_visible?
    return true unless (topic_id = self.topic_id)

    TopicQuery.new.id(topic_id).any?
  end

  table do
    belongs_to doc : Doc?
    belongs_to topic : Topic?
    has_many comments : Comment, base_query_class: CommentQuery

    polymorphic target, associations: [:doc, :topic]
    column floor_counter : Int32, autogenerated: true
  end
end
